# -*- coding: utf-8 -*-
"""Astroquery download

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pmn-ix93qJPfDCYyG5Zqqz3mVohyAxPo
"""

pip3 install astroquery pandas astropy requests

import os
import pandas as pd
import requests
from astroquery.irsa import Irsa
from astropy.coordinates import SkyCoord
import astropy.units as u

# =========================
# SETTINGS
# =========================
CATALOG = "hops_catalog.csv"
OUTDIR = "spectra"
SEARCH_RADIUS = 5 * u.arcsec  # IRS pointing tolerance

os.makedirs(OUTDIR, exist_ok=True)

# Read catalog
df = pd.read_csv(CATALOG)

print(f"Found {len(df)} HOPS targets")

# =========================
# LOOP OVER SOURCES
# =========================
for _, row in df.iterrows():
    hops_id = row["HOPS_ID"]
    ra = row["ra"]
    dec = row["dec"]

    coord = SkyCoord(ra=ra*u.deg, dec=dec*u.deg, frame="icrs")

    print(f"\n🔍 Searching IRS spectra for HOPS {hops_id}")

    try:
        # Query Spitzer observations
        table = Irsa.query_region(
            coord,
            catalog="spitzer",
            spatial="Cone",
            radius=SEARCH_RADIUS
        )

        if len(table) == 0:
            print("   ❌ No Spitzer data found")
            continue

        # Keep only IRS low-resolution spectra
        irs = table[
            (table["instrument"] == "IRS") &
            (table["resolution"] == "LOW")
        ]

        if len(irs) == 0:
            print("   ❌ No LOW-RES IRS spectra")
            continue

        # Download first matching spectrum
        url = irs["access_url"][0]
        outfile = f"{OUTDIR}/HOPS_{hops_id}_IRS_lowres.tbl"

        r = requests.get(url)
        with open(outfile, "wb") as f:
            f.write(r.content)

        print(f"   ✅ Downloaded: {outfile}")

    except Exception as e:
        print(f"   ⚠️ Error for HOPS {hops_id}: {e}")

import numpy as np
import matplotlib.pyplot as plt

data = np.genfromtxt("spectra/HOPS_12_IRS_lowres.tbl", comments="#")

wave = data[:,0]
flux = data[:,1]

plt.plot(wave, flux)
plt.xlabel("Wavelength (μm)")
plt.ylabel("Flux (Jy)")
plt.title("HOPS 12 – Spitzer IRS")
plt.show()